//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 11:13:03 AM IST 
//


package com.vsc.legacy.model.search.response;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vsc.model.search.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PrivateOccupancy_QNAME = new QName("http://ws.vacaystayconnect.com/search", "privateOccupancy");
    private final static QName _Baths_QNAME = new QName("http://ws.vacaystayconnect.com/search", "baths");
    private final static QName _PropertyName_QNAME = new QName("http://ws.vacaystayconnect.com/search", "propertyName");
    private final static QName _CityName_QNAME = new QName("http://ws.vacaystayconnect.com/search", "cityName");
    private final static QName _NonSmoking_QNAME = new QName("http://ws.vacaystayconnect.com/search", "nonSmoking");
    private final static QName _HalfBaths_QNAME = new QName("http://ws.vacaystayconnect.com/search", "halfBaths");
    private final static QName _MinOccupancy_QNAME = new QName("http://ws.vacaystayconnect.com/search", "minOccupancy");
    private final static QName _PetsAllowed_QNAME = new QName("http://ws.vacaystayconnect.com/search", "petsAllowed");
    private final static QName _AddressLine1_QNAME = new QName("http://ws.vacaystayconnect.com/search", "addressLine1");
    private final static QName _AddressLine2_QNAME = new QName("http://ws.vacaystayconnect.com/search", "addressLine2");
    private final static QName _AddressLine3_QNAME = new QName("http://ws.vacaystayconnect.com/search", "addressLine3");
    private final static QName _PropertyType_QNAME = new QName("http://ws.vacaystayconnect.com/search", "propertyType");
    private final static QName _PostalCode_QNAME = new QName("http://ws.vacaystayconnect.com/search", "postalCode");
    private final static QName _UnitName_QNAME = new QName("http://ws.vacaystayconnect.com/search", "unitName");
    private final static QName _PropertyManager_QNAME = new QName("http://ws.vacaystayconnect.com/search", "propertyManager");
    private final static QName _PropertyChainCode_QNAME = new QName("http://ws.vacaystayconnect.com/search", "propertyChainCode");
    private final static QName _MaxOccupancy_QNAME = new QName("http://ws.vacaystayconnect.com/search", "maxOccupancy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vsc.model.search.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AverageNightlyRate }
     * 
     */
    public AverageNightlyRate createAverageNightlyRate() {
        return new AverageNightlyRate();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link UnitKeyImage }
     * 
     */
    public UnitKeyImage createUnitKeyImage() {
        return new UnitKeyImage();
    }

    /**
     * Create an instance of {@link PropertyBasicInfo }
     * 
     */
    public PropertyBasicInfo createPropertyBasicInfo() {
        return new PropertyBasicInfo();
    }

    /**
     * Create an instance of {@link PropertyOwnership }
     * 
     */
    public PropertyOwnership createPropertyOwnership() {
        return new PropertyOwnership();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link StateProvince }
     * 
     */
    public StateProvince createStateProvince() {
        return new StateProvince();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link PropertyKeyImage }
     * 
     */
    public PropertyKeyImage createPropertyKeyImage() {
        return new PropertyKeyImage();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link Occupancy }
     * 
     */
    public Occupancy createOccupancy() {
        return new Occupancy();
    }

    /**
     * Create an instance of {@link Warnings }
     * 
     */
    public Warnings createWarnings() {
        return new Warnings();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link VSCSearchRS }
     * 
     */
    public VSCSearchRS createVSCSearchRS() {
        return new VSCSearchRS();
    }

    /**
     * Create an instance of {@link Success }
     * 
     */
    public Success createSuccess() {
        return new Success();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link UnitBasicInfo }
     * 
     */
    public UnitBasicInfo createUnitBasicInfo() {
        return new UnitBasicInfo();
    }

    /**
     * Create an instance of {@link BedRooms }
     * 
     */
    public BedRooms createBedRooms() {
        return new BedRooms();
    }

    /**
     * Create an instance of {@link BedTypes }
     * 
     */
    public BedTypes createBedTypes() {
        return new BedTypes();
    }

    /**
     * Create an instance of {@link BedType }
     * 
     */
    public BedType createBedType() {
        return new BedType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "privateOccupancy")
    public JAXBElement<BigInteger> createPrivateOccupancy(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrivateOccupancy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "baths")
    public JAXBElement<BigInteger> createBaths(BigInteger value) {
        return new JAXBElement<BigInteger>(_Baths_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "propertyName")
    public JAXBElement<String> createPropertyName(String value) {
        return new JAXBElement<String>(_PropertyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "cityName")
    public JAXBElement<String> createCityName(String value) {
        return new JAXBElement<String>(_CityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "nonSmoking")
    public JAXBElement<Boolean> createNonSmoking(Boolean value) {
        return new JAXBElement<Boolean>(_NonSmoking_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "halfBaths")
    public JAXBElement<String> createHalfBaths(String value) {
        return new JAXBElement<String>(_HalfBaths_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "minOccupancy")
    public JAXBElement<BigInteger> createMinOccupancy(BigInteger value) {
        return new JAXBElement<BigInteger>(_MinOccupancy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "petsAllowed")
    public JAXBElement<Boolean> createPetsAllowed(Boolean value) {
        return new JAXBElement<Boolean>(_PetsAllowed_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "addressLine1")
    public JAXBElement<String> createAddressLine1(String value) {
        return new JAXBElement<String>(_AddressLine1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "addressLine2")
    public JAXBElement<String> createAddressLine2(String value) {
        return new JAXBElement<String>(_AddressLine2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "addressLine3")
    public JAXBElement<String> createAddressLine3(String value) {
        return new JAXBElement<String>(_AddressLine3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "propertyType")
    public JAXBElement<String> createPropertyType(String value) {
        return new JAXBElement<String>(_PropertyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "postalCode")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "unitName")
    public JAXBElement<String> createUnitName(String value) {
        return new JAXBElement<String>(_UnitName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "propertyManager")
    public JAXBElement<String> createPropertyManager(String value) {
        return new JAXBElement<String>(_PropertyManager_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "propertyChainCode")
    public JAXBElement<String> createPropertyChainCode(String value) {
        return new JAXBElement<String>(_PropertyChainCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/search", name = "maxOccupancy")
    public JAXBElement<BigInteger> createMaxOccupancy(BigInteger value) {
        return new JAXBElement<BigInteger>(_MaxOccupancy_QNAME, BigInteger.class, null, value);
    }

}
