//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 11:13:03 AM IST 
//


package com.vsc.legacy.model.search.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}propertyOwnership"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}address"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}geoLocation"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}propertyKeyImage"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyOwnership",
    "address",
    "geoLocation",
    "propertyKeyImage"
})
@XmlRootElement(name = "propertyBasicInfo")
public class PropertyBasicInfo {

    @XmlElement(required = true)
    protected PropertyOwnership propertyOwnership;
    @XmlElement(required = true)
    protected Address address;
    @XmlElement(required = true)
    protected GeoLocation geoLocation;
    @XmlElement(required = true)
    protected PropertyKeyImage propertyKeyImage;

    /**
     * Gets the value of the propertyOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyOwnership }
     *     
     */
    public PropertyOwnership getPropertyOwnership() {
        return propertyOwnership;
    }

    /**
     * Sets the value of the propertyOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyOwnership }
     *     
     */
    public void setPropertyOwnership(PropertyOwnership value) {
        this.propertyOwnership = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the geoLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocation }
     *     
     */
    public GeoLocation getGeoLocation() {
        return geoLocation;
    }

    /**
     * Sets the value of the geoLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocation }
     *     
     */
    public void setGeoLocation(GeoLocation value) {
        this.geoLocation = value;
    }

    /**
     * Gets the value of the propertyKeyImage property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyKeyImage }
     *     
     */
    public PropertyKeyImage getPropertyKeyImage() {
        return propertyKeyImage;
    }

    /**
     * Sets the value of the propertyKeyImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyKeyImage }
     *     
     */
    public void setPropertyKeyImage(PropertyKeyImage value) {
        this.propertyKeyImage = value;
    }

}
