//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 11:13:03 AM IST 
//


package com.vsc.legacy.model.search.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}unitName"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}unitType"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}averageNightlyRate"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/search}unitBasicInfo"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="unitCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitName",
    "unitType",
    "averageNightlyRate",
    "unitBasicInfo"
})
@XmlRootElement(name = "unit")
public class Unit {

    @XmlElement(required = true)
    protected String unitName;
    @XmlElement(required = true)
    protected UnitType unitType;
    @XmlElement(required = true)
    protected AverageNightlyRate averageNightlyRate;
    @XmlElement(required = true)
    protected UnitBasicInfo unitBasicInfo;
    @XmlAttribute(name = "unitCode")
    protected String unitCode;

    /**
     * Gets the value of the unitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * Sets the value of the unitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitName(String value) {
        this.unitName = value;
    }

    /**
     * Gets the value of the unitType property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setUnitType(UnitType value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the averageNightlyRate property.
     * 
     * @return
     *     possible object is
     *     {@link AverageNightlyRate }
     *     
     */
    public AverageNightlyRate getAverageNightlyRate() {
        return averageNightlyRate;
    }

    /**
     * Sets the value of the averageNightlyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AverageNightlyRate }
     *     
     */
    public void setAverageNightlyRate(AverageNightlyRate value) {
        this.averageNightlyRate = value;
    }

    /**
     * Gets the value of the unitBasicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UnitBasicInfo }
     *     
     */
    public UnitBasicInfo getUnitBasicInfo() {
        return unitBasicInfo;
    }

    /**
     * Sets the value of the unitBasicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitBasicInfo }
     *     
     */
    public void setUnitBasicInfo(UnitBasicInfo value) {
        this.unitBasicInfo = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

}
