//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 11:42:18 AM IST 
//


package com.vsc.model.reserve.details.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}reservationIDs"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}unitRateType"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}stayDateRange"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}guestCounts"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}resGuests"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}resTotal"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}resComment"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="resID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"resID",
	"resStatus",
    "reservationIDs",
    "stayDateRange",
    "guestCounts",
    "resGuests",
    "unitRateType",
    "resTotal",
    "resComment"
})
@XmlRootElement(name = "reservation")
public class Reservation {

	@XmlAttribute(name = "resID")
    protected String resID;
    @XmlAttribute(name = "resStatus")
    protected String resStatus;
    @XmlElement(required = true)
    protected ReservationIDs reservationIDs;
    @XmlElement(required = true)
    protected UnitRateType unitRateType;
    @XmlElement(required = true)
    protected StayDateRange stayDateRange;
    @XmlElement(required = true)
    protected GuestCounts guestCounts;
    @XmlElement(required = true)
    protected ResGuests resGuests;
    @XmlElement(required = true)
    protected ResTotal resTotal;
    @XmlElement(required = true)
    protected String resComment;

    /**
     * Gets the value of the reservationIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationIDs }
     *     
     */
    public ReservationIDs getReservationIDs() {
        return reservationIDs;
    }

    /**
     * Sets the value of the reservationIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationIDs }
     *     
     */
    public void setReservationIDs(ReservationIDs value) {
        this.reservationIDs = value;
    }

    /**
     * Gets the value of the unitRateType property.
     * 
     * @return
     *     possible object is
     *     {@link UnitRateType }
     *     
     */
    public UnitRateType getUnitRateType() {
        return unitRateType;
    }

    /**
     * Sets the value of the unitRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitRateType }
     *     
     */
    public void setUnitRateType(UnitRateType value) {
        this.unitRateType = value;
    }

    /**
     * Gets the value of the stayDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link StayDateRange }
     *     
     */
    public StayDateRange getStayDateRange() {
        return stayDateRange;
    }

    /**
     * Sets the value of the stayDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayDateRange }
     *     
     */
    public void setStayDateRange(StayDateRange value) {
        this.stayDateRange = value;
    }

    /**
     * Gets the value of the guestCounts property.
     * 
     * @return
     *     possible object is
     *     {@link GuestCounts }
     *     
     */
    public GuestCounts getGuestCounts() {
        return guestCounts;
    }

    /**
     * Sets the value of the guestCounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuestCounts }
     *     
     */
    public void setGuestCounts(GuestCounts value) {
        this.guestCounts = value;
    }

    /**
     * Gets the value of the resGuests property.
     * 
     * @return
     *     possible object is
     *     {@link ResGuests }
     *     
     */
    public ResGuests getResGuests() {
        return resGuests;
    }

    /**
     * Sets the value of the resGuests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResGuests }
     *     
     */
    public void setResGuests(ResGuests value) {
        this.resGuests = value;
    }

    /**
     * Gets the value of the resTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ResTotal }
     *     
     */
    public ResTotal getResTotal() {
        return resTotal;
    }

    /**
     * Sets the value of the resTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResTotal }
     *     
     */
    public void setResTotal(ResTotal value) {
        this.resTotal = value;
    }

    /**
     * Gets the value of the resComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResComment() {
        return resComment;
    }

    /**
     * Sets the value of the resComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResComment(String value) {
        this.resComment = value;
    }

    /**
     * Gets the value of the resID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResID() {
        return resID;
    }

    /**
     * Sets the value of the resID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResID(String value) {
        this.resID = value;
    }

    /**
     * Gets the value of the resStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResStatus() {
        return resStatus;
    }

    /**
     * Sets the value of the resStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResStatus(String value) {
        this.resStatus = value;
    }

}
