//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 06:24:23 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.vacaystayconnect.com/quote", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vsc.model.quote.request;
