//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.05 at 02:19:16 PM IST 
//


package com.vsc.model.availability.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/avail}unitRateTypes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="propertyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"propertyCode",
    "unitRateTypes"
})
@XmlRootElement(name = "property")
public class Property {

    @XmlElement(required = true)
    protected UnitRateTypes unitRateTypes;
    @XmlAttribute(name = "propertyCode")
    protected String propertyCode;

    /**
     * Gets the value of the unitRateTypes property.
     * 
     * @return
     *     possible object is
     *     {@link UnitRateTypes }
     *     
     */
    public UnitRateTypes getUnitRateTypes() {
        return unitRateTypes;
    }

    /**
     * Sets the value of the unitRateTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitRateTypes }
     *     
     */
    public void setUnitRateTypes(UnitRateTypes value) {
        this.unitRateTypes = value;
    }

    /**
     * Gets the value of the propertyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * Sets the value of the propertyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCode(String value) {
        this.propertyCode = value;
    }

}
