//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 08:07:16 PM IST 
//


package com.vsc.model.property.details.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vsc.model.property.details.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PropertyOwnership_QNAME = new QName("http://ws.vacaystayconnect.com/propdetails", "propertyOwnership");
    private final static QName _PropertyChainCode_QNAME = new QName("http://ws.vacaystayconnect.com/propdetails", "propertyChainCode");
    private final static QName _PropertyManager_QNAME = new QName("http://ws.vacaystayconnect.com/propdetails", "propertyManager");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vsc.model.property.details.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PropertyStarRatings }
     * 
     */
    public PropertyStarRatings createPropertyStarRatings() {
        return new PropertyStarRatings();
    }

    /**
     * Create an instance of {@link PropertyStarRating }
     * 
     */
    public PropertyStarRating createPropertyStarRating() {
        return new PropertyStarRating();
    }

    /**
     * Create an instance of {@link UnitAmenities }
     * 
     */
    public UnitAmenities createUnitAmenities() {
        return new UnitAmenities();
    }

    /**
     * Create an instance of {@link UnitAmenity }
     * 
     */
    public UnitAmenity createUnitAmenity() {
        return new UnitAmenity();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link PropertyMedia }
     * 
     */
    public PropertyMedia createPropertyMedia() {
        return new PropertyMedia();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link MobileImages }
     * 
     */
    public MobileImages createMobileImages() {
        return new MobileImages();
    }

    /**
     * Create an instance of {@link MobileImage }
     * 
     */
    public MobileImage createMobileImage() {
        return new MobileImage();
    }

    /**
     * Create an instance of {@link Videos }
     * 
     */
    public Videos createVideos() {
        return new Videos();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link StateProvince }
     * 
     */
    public StateProvince createStateProvince() {
        return new StateProvince();
    }

    /**
     * Create an instance of {@link PropertyAmenity }
     * 
     */
    public PropertyAmenity createPropertyAmenity() {
        return new PropertyAmenity();
    }

    /**
     * Create an instance of {@link UnitReview }
     * 
     */
    public UnitReview createUnitReview() {
        return new UnitReview();
    }

    /**
     * Create an instance of {@link StayDetails }
     * 
     */
    public StayDetails createStayDetails() {
        return new StayDetails();
    }

    /**
     * Create an instance of {@link StarRatings }
     * 
     */
    public StarRatings createStarRatings() {
        return new StarRatings();
    }

    /**
     * Create an instance of {@link RecommendTo }
     * 
     */
    public RecommendTo createRecommendTo() {
        return new RecommendTo();
    }

    /**
     * Create an instance of {@link MgmtFollowup }
     * 
     */
    public MgmtFollowup createMgmtFollowup() {
        return new MgmtFollowup();
    }

    /**
     * Create an instance of {@link VSCPropertyDetailsRS }
     * 
     */
    public VSCPropertyDetailsRS createVSCPropertyDetailsRS() {
        return new VSCPropertyDetailsRS();
    }

    /**
     * Create an instance of {@link Success }
     * 
     */
    public Success createSuccess() {
        return new Success();
    }

    /**
     * Create an instance of {@link Warnings }
     * 
     */
    public Warnings createWarnings() {
        return new Warnings();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link PropertyDetails }
     * 
     */
    public PropertyDetails createPropertyDetails() {
        return new PropertyDetails();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link DescriptiveTexts }
     * 
     */
    public DescriptiveTexts createDescriptiveTexts() {
        return new DescriptiveTexts();
    }

    /**
     * Create an instance of {@link DescriptiveText }
     * 
     */
    public DescriptiveText createDescriptiveText() {
        return new DescriptiveText();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link NearestAirport }
     * 
     */
    public NearestAirport createNearestAirport() {
        return new NearestAirport();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link ContactName }
     * 
     */
    public ContactName createContactName() {
        return new ContactName();
    }

    /**
     * Create an instance of {@link PhoneNumbers }
     * 
     */
    public PhoneNumbers createPhoneNumbers() {
        return new PhoneNumbers();
    }

    /**
     * Create an instance of {@link EmailAddresses }
     * 
     */
    public EmailAddresses createEmailAddresses() {
        return new EmailAddresses();
    }

    /**
     * Create an instance of {@link EmailAddress }
     * 
     */
    public EmailAddress createEmailAddress() {
        return new EmailAddress();
    }

    /**
     * Create an instance of {@link PropertyAmenities }
     * 
     */
    public PropertyAmenities createPropertyAmenities() {
        return new PropertyAmenities();
    }

    /**
     * Create an instance of {@link PropertyActivities }
     * 
     */
    public PropertyActivities createPropertyActivities() {
        return new PropertyActivities();
    }

    /**
     * Create an instance of {@link PropertyActivity }
     * 
     */
    public PropertyActivity createPropertyActivity() {
        return new PropertyActivity();
    }

    /**
     * Create an instance of {@link AgeGroup }
     * 
     */
    public AgeGroup createAgeGroup() {
        return new AgeGroup();
    }

    /**
     * Create an instance of {@link PropertyReviews }
     * 
     */
    public PropertyReviews createPropertyReviews() {
        return new PropertyReviews();
    }

    /**
     * Create an instance of {@link PropertyReview }
     * 
     */
    public PropertyReview createPropertyReview() {
        return new PropertyReview();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link UnitSpace }
     * 
     */
    public UnitSpace createUnitSpace() {
        return new UnitSpace();
    }

    /**
     * Create an instance of {@link Occupancy }
     * 
     */
    public Occupancy createOccupancy() {
        return new Occupancy();
    }

    /**
     * Create an instance of {@link Bedrooms }
     * 
     */
    public Bedrooms createBedrooms() {
        return new Bedrooms();
    }

    /**
     * Create an instance of {@link Bedroom }
     * 
     */
    public Bedroom createBedroom() {
        return new Bedroom();
    }

    /**
     * Create an instance of {@link Bed }
     * 
     */
    public Bed createBed() {
        return new Bed();
    }

    /**
     * Create an instance of {@link UnitMedia }
     * 
     */
    public UnitMedia createUnitMedia() {
        return new UnitMedia();
    }

    /**
     * Create an instance of {@link UnitReviews }
     * 
     */
    public UnitReviews createUnitReviews() {
        return new UnitReviews();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/propdetails", name = "propertyOwnership")
    public JAXBElement<Object> createPropertyOwnership(Object value) {
        return new JAXBElement<Object>(_PropertyOwnership_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/propdetails", name = "propertyChainCode")
    public JAXBElement<String> createPropertyChainCode(String value) {
        return new JAXBElement<String>(_PropertyChainCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/propdetails", name = "propertyManager")
    public JAXBElement<String> createPropertyManager(String value) {
        return new JAXBElement<String>(_PropertyManager_QNAME, String.class, null, value);
    }

}
