//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 08:07:16 PM IST 
//


package com.vsc.model.property.details.response;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="unitName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="unitType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}unitSpace"/>
 *           &lt;element name="numberOfFloors" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *           &lt;element name="floorNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="numberOfGarages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="numberOfLofts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="yearBuilt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="petsAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="nonSmoking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}addresses"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}descriptiveTexts"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}occupancy"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}bedrooms"/>
 *           &lt;element name="baths" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="halfBaths" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}unitAmenities"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}unitMedia"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}unitReviews"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="unitCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitName",
    "unitType",
    "unitSpace",
    "numberOfFloors",
    "floorNumber",
    "numberOfGarages",
    "numberOfLofts",
    "yearBuilt",
    "petsAllowed",
    "nonSmoking",
    "addresses",
    "descriptiveTexts",
    "occupancy",
    "bedrooms",
    "baths",
    "halfBaths",
    "unitAmenities",
    "unitMedia",
    "unitReviews"
})
@XmlRootElement(name = "unit")
public class Unit {

    @XmlElement(required = true)
    protected String unitName;
    @XmlElement(required = true)
    protected String unitType;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected UnitSpace unitSpace;
    @XmlElement(required = true)
    protected BigInteger numberOfFloors;
    @XmlElement(required = true)
    protected String floorNumber;
    @XmlElement(required = true)
    protected String numberOfGarages;
    @XmlElement(required = true)
    protected String numberOfLofts;
    @XmlElement(required = true)
    protected String yearBuilt;
    @XmlElement(required = true)
    protected String petsAllowed;
    @XmlElement(required = true)
    protected String nonSmoking;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Addresses addresses;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected DescriptiveTexts descriptiveTexts;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Occupancy occupancy;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Bedrooms bedrooms;
    protected float baths;
    @XmlElement(required = true)
    protected BigInteger halfBaths;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected UnitAmenities unitAmenities;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected UnitMedia unitMedia;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected UnitReviews unitReviews;
    @XmlAttribute(name = "unitCode")
    protected String unitCode;

    /**
     * Gets the value of the unitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * Sets the value of the unitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitName(String value) {
        this.unitName = value;
    }

    /**
     * Gets the value of the unitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitType(String value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the unitSpace property.
     * 
     * @return
     *     possible object is
     *     {@link UnitSpace }
     *     
     */
    public UnitSpace getUnitSpace() {
        return unitSpace;
    }

    /**
     * Sets the value of the unitSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitSpace }
     *     
     */
    public void setUnitSpace(UnitSpace value) {
        this.unitSpace = value;
    }

    /**
     * Gets the value of the numberOfFloors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfFloors() {
        return numberOfFloors;
    }

    /**
     * Sets the value of the numberOfFloors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfFloors(BigInteger value) {
        this.numberOfFloors = value;
    }

    /**
     * Gets the value of the floorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloorNumber() {
        return floorNumber;
    }

    /**
     * Sets the value of the floorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloorNumber(String value) {
        this.floorNumber = value;
    }

    /**
     * Gets the value of the numberOfGarages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfGarages() {
        return numberOfGarages;
    }

    /**
     * Sets the value of the numberOfGarages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfGarages(String value) {
        this.numberOfGarages = value;
    }

    /**
     * Gets the value of the numberOfLofts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfLofts() {
        return numberOfLofts;
    }

    /**
     * Sets the value of the numberOfLofts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfLofts(String value) {
        this.numberOfLofts = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearBuilt(String value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the petsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPetsAllowed() {
        return petsAllowed;
    }

    /**
     * Sets the value of the petsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPetsAllowed(String value) {
        this.petsAllowed = value;
    }

    /**
     * Gets the value of the nonSmoking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonSmoking() {
        return nonSmoking;
    }

    /**
     * Sets the value of the nonSmoking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonSmoking(String value) {
        this.nonSmoking = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the descriptiveTexts property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveTexts }
     *     
     */
    public DescriptiveTexts getDescriptiveTexts() {
        return descriptiveTexts;
    }

    /**
     * Sets the value of the descriptiveTexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveTexts }
     *     
     */
    public void setDescriptiveTexts(DescriptiveTexts value) {
        this.descriptiveTexts = value;
    }

    /**
     * Gets the value of the occupancy property.
     * 
     * @return
     *     possible object is
     *     {@link Occupancy }
     *     
     */
    public Occupancy getOccupancy() {
        return occupancy;
    }

    /**
     * Sets the value of the occupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Occupancy }
     *     
     */
    public void setOccupancy(Occupancy value) {
        this.occupancy = value;
    }

    /**
     * Gets the value of the bedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Bedrooms }
     *     
     */
    public Bedrooms getBedrooms() {
        return bedrooms;
    }

    /**
     * Sets the value of the bedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bedrooms }
     *     
     */
    public void setBedrooms(Bedrooms value) {
        this.bedrooms = value;
    }

    /**
     * Gets the value of the baths property.
     * 
     */
    public float getBaths() {
        return baths;
    }

    /**
     * Sets the value of the baths property.
     * 
     */
    public void setBaths(float value) {
        this.baths = value;
    }

    /**
     * Gets the value of the halfBaths property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHalfBaths() {
        return halfBaths;
    }

    /**
     * Sets the value of the halfBaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHalfBaths(BigInteger value) {
        this.halfBaths = value;
    }

    /**
     * Gets the value of the unitAmenities property.
     * 
     * @return
     *     possible object is
     *     {@link UnitAmenities }
     *     
     */
    public UnitAmenities getUnitAmenities() {
        return unitAmenities;
    }

    /**
     * Sets the value of the unitAmenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitAmenities }
     *     
     */
    public void setUnitAmenities(UnitAmenities value) {
        this.unitAmenities = value;
    }

    /**
     * Gets the value of the unitMedia property.
     * 
     * @return
     *     possible object is
     *     {@link UnitMedia }
     *     
     */
    public UnitMedia getUnitMedia() {
        return unitMedia;
    }

    /**
     * Sets the value of the unitMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitMedia }
     *     
     */
    public void setUnitMedia(UnitMedia value) {
        this.unitMedia = value;
    }

    /**
     * Gets the value of the unitReviews property.
     * 
     * @return
     *     possible object is
     *     {@link UnitReviews }
     *     
     */
    public UnitReviews getUnitReviews() {
        return unitReviews;
    }

    /**
     * Sets the value of the unitReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitReviews }
     *     
     */
    public void setUnitReviews(UnitReviews value) {
        this.unitReviews = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

}
