//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 12:50:17 PM IST 
//


package com.vsc.legacy.model.reserve.request;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/reserve}resGuest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resGuest"
})
@XmlRootElement(name = "resGuests")
public class ResGuests {

    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected ResGuest resGuest;

    /**
     * Gets the value of the resGuest property.
     * 
     * @return
     *     possible object is
     *     {@link ResGuest }
     *     
     */
    public ResGuest getResGuest() {
        return resGuest;
    }

    /**
     * Sets the value of the resGuest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResGuest }
     *     
     */
    public void setResGuest(ResGuest value) {
        this.resGuest = value;
    }

}
