//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 08:07:16 PM IST 
//


package com.vsc.legacy.model.property.details.response;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="propertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="propertyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}accommodationType"/>
 *         &lt;element name="complexName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyOwnership"/>
 *         &lt;element name="numberOfFloors" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="checkInTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="checkOutTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberOfRestaurants" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="numberOfMeetingRooms" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyStarRatings"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}descriptiveTexts"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}addresses"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}geoLocation"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}nearestAirport"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}contactDetails"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyAmenities"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyActivities"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyMedia"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}propertyReviews"/>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/propdetails}units"/>
 *       &lt;/sequence>
 *       &lt;attribute name="propertyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyName",
    "propertyType",
    "accommodationType",
    "complexName",
    "propertyOwnership",
    "numberOfFloors",
    "checkInTime",
    "checkOutTime",
    "numberOfRestaurants",
    "numberOfMeetingRooms",
    "propertyStarRatings",
    "descriptiveTexts",
    "addresses",
    "geoLocation",
    "nearestAirport",
    "contactDetails",
    "propertyAmenities",
    "propertyActivities",
    "propertyMedia",
    "propertyReviews",
    "units"
})
@XmlRootElement(name = "property")
public class Property {

    @XmlElement(required = true)
    protected String propertyName;
    @XmlElement(required = true)
    protected String propertyType;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected AccommodationType accommodationType;
    @XmlElement(required = true)
    protected String complexName;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Object propertyOwnership;
    protected byte numberOfFloors;
    @XmlElement(required = true)
    protected String checkInTime;
    @XmlElement(required = true)
    protected String checkOutTime;
    @XmlElement(required = true)
    protected BigInteger numberOfRestaurants;
    @XmlElement(required = true)
    protected BigInteger numberOfMeetingRooms;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected PropertyStarRatings propertyStarRatings;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected DescriptiveTexts descriptiveTexts;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Addresses addresses;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected GeoLocation geoLocation;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected NearestAirport nearestAirport;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected ContactDetails contactDetails;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected PropertyAmenities propertyAmenities;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected PropertyActivities propertyActivities;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected PropertyMedia propertyMedia;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected PropertyReviews propertyReviews;
    @XmlElement(namespace = "http://ws.vacaystayconnect.com/propdetails", required = true)
    protected Units units;
    @XmlAttribute(name = "propertyCode")
    protected String propertyCode;

    /**
     * Gets the value of the propertyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyName(String value) {
        this.propertyName = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the accommodationType property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationType }
     *     
     */
    public AccommodationType getAccommodationType() {
        return accommodationType;
    }

    /**
     * Sets the value of the accommodationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationType }
     *     
     */
    public void setAccommodationType(AccommodationType value) {
        this.accommodationType = value;
    }

    /**
     * Gets the value of the complexName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplexName() {
        return complexName;
    }

    /**
     * Sets the value of the complexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplexName(String value) {
        this.complexName = value;
    }

    /**
     * Gets the value of the propertyOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPropertyOwnership() {
        return propertyOwnership;
    }

    /**
     * Sets the value of the propertyOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPropertyOwnership(Object value) {
        this.propertyOwnership = value;
    }

    /**
     * Gets the value of the numberOfFloors property.
     * 
     */
    public byte getNumberOfFloors() {
        return numberOfFloors;
    }

    /**
     * Sets the value of the numberOfFloors property.
     * 
     */
    public void setNumberOfFloors(byte value) {
        this.numberOfFloors = value;
    }

    /**
     * Gets the value of the checkInTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckInTime() {
        return checkInTime;
    }

    /**
     * Sets the value of the checkInTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckInTime(String value) {
        this.checkInTime = value;
    }

    /**
     * Gets the value of the checkOutTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * Sets the value of the checkOutTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckOutTime(String value) {
        this.checkOutTime = value;
    }

    /**
     * Gets the value of the numberOfRestaurants property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfRestaurants() {
        return numberOfRestaurants;
    }

    /**
     * Sets the value of the numberOfRestaurants property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfRestaurants(BigInteger value) {
        this.numberOfRestaurants = value;
    }

    /**
     * Gets the value of the numberOfMeetingRooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfMeetingRooms() {
        return numberOfMeetingRooms;
    }

    /**
     * Sets the value of the numberOfMeetingRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfMeetingRooms(BigInteger value) {
        this.numberOfMeetingRooms = value;
    }

    /**
     * Gets the value of the propertyStarRatings property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyStarRatings }
     *     
     */
    public PropertyStarRatings getPropertyStarRatings() {
        return propertyStarRatings;
    }

    /**
     * Sets the value of the propertyStarRatings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyStarRatings }
     *     
     */
    public void setPropertyStarRatings(PropertyStarRatings value) {
        this.propertyStarRatings = value;
    }

    /**
     * Gets the value of the descriptiveTexts property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveTexts }
     *     
     */
    public DescriptiveTexts getDescriptiveTexts() {
        return descriptiveTexts;
    }

    /**
     * Sets the value of the descriptiveTexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveTexts }
     *     
     */
    public void setDescriptiveTexts(DescriptiveTexts value) {
        this.descriptiveTexts = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the geoLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocation }
     *     
     */
    public GeoLocation getGeoLocation() {
        return geoLocation;
    }

    /**
     * Sets the value of the geoLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocation }
     *     
     */
    public void setGeoLocation(GeoLocation value) {
        this.geoLocation = value;
    }

    /**
     * Gets the value of the nearestAirport property.
     * 
     * @return
     *     possible object is
     *     {@link NearestAirport }
     *     
     */
    public NearestAirport getNearestAirport() {
        return nearestAirport;
    }

    /**
     * Sets the value of the nearestAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link NearestAirport }
     *     
     */
    public void setNearestAirport(NearestAirport value) {
        this.nearestAirport = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetails }
     *     
     */
    public ContactDetails getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetails }
     *     
     */
    public void setContactDetails(ContactDetails value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the propertyAmenities property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyAmenities }
     *     
     */
    public PropertyAmenities getPropertyAmenities() {
        return propertyAmenities;
    }

    /**
     * Sets the value of the propertyAmenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyAmenities }
     *     
     */
    public void setPropertyAmenities(PropertyAmenities value) {
        this.propertyAmenities = value;
    }

    /**
     * Gets the value of the propertyActivities property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyActivities }
     *     
     */
    public PropertyActivities getPropertyActivities() {
        return propertyActivities;
    }

    /**
     * Sets the value of the propertyActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyActivities }
     *     
     */
    public void setPropertyActivities(PropertyActivities value) {
        this.propertyActivities = value;
    }

    /**
     * Gets the value of the propertyMedia property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyMedia }
     *     
     */
    public PropertyMedia getPropertyMedia() {
        return propertyMedia;
    }

    /**
     * Sets the value of the propertyMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyMedia }
     *     
     */
    public void setPropertyMedia(PropertyMedia value) {
        this.propertyMedia = value;
    }

    /**
     * Gets the value of the propertyReviews property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyReviews }
     *     
     */
    public PropertyReviews getPropertyReviews() {
        return propertyReviews;
    }

    /**
     * Sets the value of the propertyReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyReviews }
     *     
     */
    public void setPropertyReviews(PropertyReviews value) {
        this.propertyReviews = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Units }
     *     
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Units }
     *     
     */
    public void setUnits(Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the propertyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * Sets the value of the propertyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCode(String value) {
        this.propertyCode = value;
    }

}
