//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.22 at 12:21:11 PM IST 
//


package com.vsc.legacy.model.reserve.details.request;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.vsc.legacy.model.common.BaseModel;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}pos"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/retrieveresdtls}retrieveResDetails"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"timeStamp",
    "pos",
    "retrieveResDetails"
})
@XmlRootElement(name = "VSC_RetrieveResDetailsRQ")
public class VSCRetrieveResDetailsRQ extends BaseModel {

    @XmlElement(required = true)
    @Valid
    protected Pos pos;
    @XmlElement(required = true)
    @Valid
	@NotNull(message = "{010}")
    protected RetrieveResDetails retrieveResDetails;
    @XmlAttribute(name = "timeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link Pos }
     *     
     */
    public Pos getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pos }
     *     
     */
    public void setPos(Pos value) {
        this.pos = value;
    }

    /**
     * Gets the value of the retrieveResDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RetrieveResDetails }
     *     
     */
    public RetrieveResDetails getRetrieveResDetails() {
        return retrieveResDetails;
    }

    /**
     * Sets the value of the retrieveResDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrieveResDetails }
     *     
     */
    public void setRetrieveResDetails(RetrieveResDetails value) {
        this.retrieveResDetails = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

}
