//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 04:47:09 PM IST 
//


package com.vsc.legacy.model.reserve.cancel.request;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/cancel}reservationID"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/cancel}cancellationComment"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reservationID",
    "cancellationComment"
})
@XmlRootElement(name = "cancelRequest")
public class CancelRequest {

    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected ReservationID reservationID;
    @XmlElement(required = true)
    protected String cancellationComment;

    /**
     * Gets the value of the reservationID property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationID }
     *     
     */
    public ReservationID getReservationID() {
        return reservationID;
    }

    /**
     * Sets the value of the reservationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationID }
     *     
     */
    public void setReservationID(ReservationID value) {
        this.reservationID = value;
    }

    /**
     * Gets the value of the cancellationComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationComment() {
        return cancellationComment;
    }

    /**
     * Sets the value of the cancellationComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationComment(String value) {
        this.cancellationComment = value;
    }

}
