//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 04:47:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.vacaystayconnect.com/cancel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vsc.legacy.model.reserve.cancel.request;
