//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 12:50:17 PM IST 
//


package com.vsc.model.reserve.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vibes.neo.model.reserve.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PostalCode_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "postalCode");
    private final static QName _ResComment_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "resComment");
    private final static QName _LastName_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "lastName");
    private final static QName _CityName_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "cityName");
    private final static QName _Source_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "source");
    private final static QName _AddressLine1_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "addressLine1");
    private final static QName _AddressLine2_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "addressLine2");
    private final static QName _AddressLine3_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "addressLine3");
    private final static QName _FirstName_QNAME = new QName("http://ws.vacaystayconnect.com/reserve", "firstName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vibes.neo.model.reserve.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VSCReserveRQ }
     * 
     */
    public VSCReserveRQ createVSCReserveRQ() {
        return new VSCReserveRQ();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link Reservations }
     * 
     */
    public Reservations createReservations() {
        return new Reservations();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link UnitRateType }
     * 
     */
    public UnitRateType createUnitRateType() {
        return new UnitRateType();
    }

    /**
     * Create an instance of {@link Rates }
     * 
     */
    public Rates createRates() {
        return new Rates();
    }

    /**
     * Create an instance of {@link Rate }
     * 
     */
    public Rate createRate() {
        return new Rate();
    }

    /**
     * Create an instance of {@link Fees }
     * 
     */
    public Fees createFees() {
        return new Fees();
    }

    /**
     * Create an instance of {@link Fee }
     * 
     */
    public Fee createFee() {
        return new Fee();
    }

    /**
     * Create an instance of {@link Taxes }
     * 
     */
    public Taxes createTaxes() {
        return new Taxes();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link StayDateRange }
     * 
     */
    public StayDateRange createStayDateRange() {
        return new StayDateRange();
    }

    /**
     * Create an instance of {@link GuestCounts }
     * 
     */
    public GuestCounts createGuestCounts() {
        return new GuestCounts();
    }

    /**
     * Create an instance of {@link ResGuests }
     * 
     */
    public ResGuests createResGuests() {
        return new ResGuests();
    }

    /**
     * Create an instance of {@link ResGuest }
     * 
     */
    public ResGuest createResGuest() {
        return new ResGuest();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link ContactName }
     * 
     */
    public ContactName createContactName() {
        return new ContactName();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link EmailAddress }
     * 
     */
    public EmailAddress createEmailAddress() {
        return new EmailAddress();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link StateProvince }
     * 
     */
    public StateProvince createStateProvince() {
        return new StateProvince();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link ResTotal }
     * 
     */
    public ResTotal createResTotal() {
        return new ResTotal();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Payments }
     * 
     */
    public Payments createPayments() {
        return new Payments();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "postalCode")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "resComment")
    public JAXBElement<String> createResComment(String value) {
        return new JAXBElement<String>(_ResComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "lastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "cityName")
    public JAXBElement<String> createCityName(String value) {
        return new JAXBElement<String>(_CityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "addressLine1")
    public JAXBElement<String> createAddressLine1(String value) {
        return new JAXBElement<String>(_AddressLine1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "addressLine2")
    public JAXBElement<String> createAddressLine2(String value) {
        return new JAXBElement<String>(_AddressLine2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "addressLine3")
    public JAXBElement<String> createAddressLine3(String value) {
        return new JAXBElement<String>(_AddressLine3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/reserve", name = "firstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

}
