//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 12:50:17 PM IST 
//


package com.vsc.model.reserve.request;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.vsc.validation.contraints.ReservationValidation;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}unitRateType"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}stayDateRange"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}guestCounts"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}resGuests"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}resTotal"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}resComment"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/reserve}payment"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitRateType",
    "stayDateRange",
    "guestCounts",
    "resGuests",
    "resTotal",
    "resComment"
})
@XmlRootElement(name = "reservation")
@ReservationValidation(stayDateRange = "stayDateRange", unitRateType = "unitRateType", resTotal = "resTotal", guestCounts = "guestCounts")
public class Reservation {

    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected UnitRateType unitRateType;
    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected StayDateRange stayDateRange;
    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected GuestCounts guestCounts;
    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected ResGuests resGuests;
    @XmlElement(required = true)
    @Valid
    @NotNull(message = "{010}")
    protected ResTotal resTotal;
    @XmlElement(required = true)
    @NotNull(message = "{010}")
    protected String resComment;

    /**
     * Gets the value of the unitRateType property.
     * 
     * @return
     *     possible object is
     *     {@link UnitRateType }
     *     
     */
    public UnitRateType getUnitRateType() {
        return unitRateType;
    }

    /**
     * Sets the value of the unitRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitRateType }
     *     
     */
    public void setUnitRateType(UnitRateType value) {
        this.unitRateType = value;
    }

    /**
     * Gets the value of the stayDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link StayDateRange }
     *     
     */
    public StayDateRange getStayDateRange() {
        return stayDateRange;
    }

    /**
     * Sets the value of the stayDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayDateRange }
     *     
     */
    public void setStayDateRange(StayDateRange value) {
        this.stayDateRange = value;
    }

    /**
     * Gets the value of the guestCounts property.
     * 
     * @return
     *     possible object is
     *     {@link GuestCounts }
     *     
     */
    public GuestCounts getGuestCounts() {
        return guestCounts;
    }

    /**
     * Sets the value of the guestCounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuestCounts }
     *     
     */
    public void setGuestCounts(GuestCounts value) {
        this.guestCounts = value;
    }

    /**
     * Gets the value of the resGuests property.
     * 
     * @return
     *     possible object is
     *     {@link ResGuests }
     *     
     */
    public ResGuests getResGuests() {
        return resGuests;
    }

    /**
     * Sets the value of the resGuests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResGuests }
     *     
     */
    public void setResGuests(ResGuests value) {
        this.resGuests = value;
    }

    /**
     * Gets the value of the resTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ResTotal }
     *     
     */
    public ResTotal getResTotal() {
        return resTotal;
    }

    /**
     * Sets the value of the resTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResTotal }
     *     
     */
    public void setResTotal(ResTotal value) {
        this.resTotal = value;
    }

    /**
     * Gets the value of the resComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResComment() {
        return resComment;
    }

    /**
     * Sets the value of the resComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResComment(String value) {
        this.resComment = value;
    }

}
