//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 07:14:57 PM IST 
//


package com.vsc.model.quote.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ws.vacaystayconnect.com/quote}unitRateTypes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitRateTypes"
})
@XmlRootElement(name = "quoteResponse")
public class QuoteResponse {

    @XmlElement(required = true)
    protected UnitRateTypes unitRateTypes;

    /**
     * Gets the value of the unitRateTypes property.
     * 
     * @return
     *     possible object is
     *     {@link UnitRateTypes }
     *     
     */
    public UnitRateTypes getUnitRateTypes() {
        return unitRateTypes;
    }

    /**
     * Sets the value of the unitRateTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitRateTypes }
     *     
     */
    public void setUnitRateTypes(UnitRateTypes value) {
        this.unitRateTypes = value;
    }

}
