//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 07:14:57 PM IST 
//


package com.vsc.model.quote.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}rates"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}fees"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}services"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}taxes"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}paymentSchedules"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}stayDateRange"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}guestCounts"/>
 *           &lt;element ref="{http://ws.vacaystayconnect.com/quote}pets"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="availableUnits" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="unitCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rates",
    "fees",
    "services",
    "taxes",
    "paymentSchedules",
    "stayDateRange",
    "guestCounts",
    "pets"
})
@XmlRootElement(name = "unit")
public class Unit {

    @XmlElement(required = true)
    protected Rates rates;
    @XmlElement(required = true)
    protected Fees fees;
    @XmlElement(required = true)
    protected Services services;
    @XmlElement(required = true)
    protected Taxes taxes;
    @XmlElement(required = true)
    protected PaymentSchedules paymentSchedules;
    @XmlElement(required = true)
    protected StayDateRange stayDateRange;
    @XmlElement(required = true)
    protected GuestCounts guestCounts;
    @XmlElement(required = true)
    protected Pets pets;
    @XmlAttribute(name = "availableUnits")
    protected Boolean availableUnits;
    @XmlAttribute(name = "unitCode")
    protected String unitCode;

    /**
     * Gets the value of the rates property.
     * 
     * @return
     *     possible object is
     *     {@link Rates }
     *     
     */
    public Rates getRates() {
        return rates;
    }

    /**
     * Sets the value of the rates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rates }
     *     
     */
    public void setRates(Rates value) {
        this.rates = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link Fees }
     *     
     */
    public Fees getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fees }
     *     
     */
    public void setFees(Fees value) {
        this.fees = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link Services }
     *     
     */
    public Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link Services }
     *     
     */
    public void setServices(Services value) {
        this.services = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     * @return
     *     possible object is
     *     {@link Taxes }
     *     
     */
    public Taxes getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Taxes }
     *     
     */
    public void setTaxes(Taxes value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the paymentSchedules property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentSchedules }
     *     
     */
    public PaymentSchedules getPaymentSchedules() {
        return paymentSchedules;
    }

    /**
     * Sets the value of the paymentSchedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentSchedules }
     *     
     */
    public void setPaymentSchedules(PaymentSchedules value) {
        this.paymentSchedules = value;
    }

    /**
     * Gets the value of the stayDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link StayDateRange }
     *     
     */
    public StayDateRange getStayDateRange() {
        return stayDateRange;
    }

    /**
     * Sets the value of the stayDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayDateRange }
     *     
     */
    public void setStayDateRange(StayDateRange value) {
        this.stayDateRange = value;
    }

    /**
     * Gets the value of the guestCounts property.
     * 
     * @return
     *     possible object is
     *     {@link GuestCounts }
     *     
     */
    public GuestCounts getGuestCounts() {
        return guestCounts;
    }

    /**
     * Sets the value of the guestCounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuestCounts }
     *     
     */
    public void setGuestCounts(GuestCounts value) {
        this.guestCounts = value;
    }

    /**
     * Gets the value of the pets property.
     * 
     * @return
     *     possible object is
     *     {@link Pets }
     *     
     */
    public Pets getPets() {
        return pets;
    }

    /**
     * Sets the value of the pets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pets }
     *     
     */
    public void setPets(Pets value) {
        this.pets = value;
    }

    /**
     * Gets the value of the availableUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvailableUnits() {
        return availableUnits;
    }

    /**
     * Sets the value of the availableUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvailableUnits(Boolean value) {
        this.availableUnits = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

}
