//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 07:13:03 PM IST 
//


package com.vsc.model.reserve.cancel.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vsc.model.reserve.cancel.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancellationDate_QNAME = new QName("http://ws.vacaystayconnect.com/cancel", "cancellationDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vsc.model.reserve.cancel.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link CancellationReason }
     * 
     */
    public CancellationReason createCancellationReason() {
        return new CancellationReason();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link VSCCancelRS }
     * 
     */
    public VSCCancelRS createVSCCancelRS() {
        return new VSCCancelRS();
    }

    /**
     * Create an instance of {@link Success }
     * 
     */
    public Success createSuccess() {
        return new Success();
    }

    /**
     * Create an instance of {@link Warnings }
     * 
     */
    public Warnings createWarnings() {
        return new Warnings();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link Cancellations }
     * 
     */
    public Cancellations createCancellations() {
        return new Cancellations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/cancel", name = "cancellationDate")
    public JAXBElement<XMLGregorianCalendar> createCancellationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CancellationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
