//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 04:47:09 PM IST 
//


package com.vsc.model.reserve.cancel.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vibes.neo.model.reserve.cancel.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("http://ws.vacaystayconnect.com/cancel", "source");
    private final static QName _CancellationComment_QNAME = new QName("http://ws.vacaystayconnect.com/cancel", "cancellationComment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vibes.neo.model.reserve.cancel.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReservationID }
     * 
     */
    public ReservationID createReservationID() {
        return new ReservationID();
    }

    /**
     * Create an instance of {@link CancelRequest }
     * 
     */
    public CancelRequest createCancelRequest() {
        return new CancelRequest();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link VSCCancelRQ }
     * 
     */
    public VSCCancelRQ createVSCCancelRQ() {
        return new VSCCancelRQ();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/cancel", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.vacaystayconnect.com/cancel", name = "cancellationComment")
    public JAXBElement<String> createCancellationComment(String value) {
        return new JAXBElement<String>(_CancellationComment_QNAME, String.class, null, value);
    }

}
