//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 02:43:34 PM IST 
//


package com.vsc.model.availability.request;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.validator.constraints.NotEmpty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}pos"/>
 *           &lt;element ref="{}availabilityRequest"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pos",
    "availabilityRequest"
})
@XmlRootElement(name = "VSC_AvailRQ")
@JsonIgnoreProperties(ignoreUnknown=true)
public class VSCAvailRQ {

    @XmlElement(required = true)
    @NotNull(message = "{010}")
	@Valid
    protected Pos pos;
    @XmlElement(required = true)
    @Valid
	@NotNull(message = "{010}")
    protected AvailabilityRequest availabilityRequest;
    @XmlAttribute(name = "timeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link Pos }
     *     
     */
    public Pos getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pos }
     *     
     */
    public void setPos(Pos value) {
        this.pos = value;
    }

    /**
     * Gets the value of the availabilityRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityRequest }
     *     
     */
    public AvailabilityRequest getAvailabilityRequest() {
        return availabilityRequest;
    }

    /**
     * Sets the value of the availabilityRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityRequest }
     *     
     */
    public void setAvailabilityRequest(AvailabilityRequest value) {
        this.availabilityRequest = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
            return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

}
