//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.05 at 02:19:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.vacaystayconnect.com/avail", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vsc.legacy.model.availability.request;
